# For whatever reason, helix disables autoformatting by default for many languages.

[[language]]
name = "python"
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "nix"
language-servers = ["nixd"]
auto-format = true
formatter = { command = "nixpkgs-fmt" }

[language-server.nixd]
command = "nixd"
