[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
format = " $title.str(max_w:21) | Missing "

[[block]]
block = "music"

# Left click already used for buttons
[[block.click]]
button = "right"
cmd = "flatpak run com.spotify.Client"

# BT mouse
[[block]]
block = "bluetooth"
mac = "D4:D4:6C:06:E8:62"
disconnected_format = ""
format = " $icon "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /: $available "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents "
format_alt = " $icon $swap_used_percents "

[[block]]
block = "net"
format = " $icon { $signal_strength $ssid $frequency|  } $ip "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "battery"
device = "BAT0"
missing_format = ""

[[block]]
block = "kdeconnect"
format = " $icon {$bat_charge|} "
hide_disconnected = false
[[block.click]]
button = "left"
cmd = "kdeconnect-app"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# Galaxy Buds
[[block]]
block = "bluetooth"
mac = "38:8F:30:58:34:A8"
disconnected_format = " $icon "
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..50" = "warning"
"51..100" = "good"
[[block.click]]
button = "right"
cmd = "galaxybudsclient"
[[block.click]]
button = "left"
cmd = "blueman-manager"

[[block]]
block = "backlight"

# TODO: Implement mako support and enable
#[[block]]
#block = "notify"
#format = " $icon {$paused{Off}|On} "

[[block]]
block = "weather"
format = " $icon $weather $temp "
autolocate = true
[block.service]
name = "metno"
units = "metric"

[[block]]
block = "time"