[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome"

[[block]]
block = "focused_window"
format = " $title.str(0,24) | Missing "

[[block]]
block = "music"
format = " $icon {$combo.str(0,20) $play $next |}"
# Left click already used for buttons
[[block.click]]
button = "right"
cmd = "flatpak run com.spotify.Client"

# BT headset
[[block]]
block = "bluetooth"
mac = "60:C5:E6:17:5C:B5"
disconnected_format = ""
format = " $icon "

# BT mouse
[[block]]
block = "bluetooth"
mac = "D4:D4:6C:06:E8:62"
disconnected_format = ""
format = " $icon "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon /: $available.eng(2) "

[[block]]
block = "memory"
display_type = "memory"
format_mem = " $icon $mem_total_used_percents.eng(2) "
format_swap = " $icon $swap_used_percents.eng(2) "

[[block]]
block = "net"
format = " $icon {  $signal_strength $ssid $frequency|  } $ip "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "battery"
device = "BAT0"
missing_format = ""

[[block]]
block = "kdeconnect"
format = " $icon {$bat_charge|} "
hide_disconnected = false
[[block.click]]
button = "left"
cmd = "kdeconnect-app"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"

# TODO: Implement mako support and enable
#[[block]]
#block = "notify"
#format = " $icon {$paused{Off}|On} "

[[block]]
block = "weather"
format = " $icon $weather $temp "
autolocate = true
[block.service]
name = "metno"
units = "metric"

[[block]]
block = "time"
interval = 5
format = " %a %d.%m.%y %R "
